// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsumerBasicAuthArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsumerBasicAuthArgs Empty = new ConsumerBasicAuthArgs();

    /**
     * the id of the consumer to be configured with basic auth
     * 
     */
    @Import(name="consumerId", required=true)
    private Output<String> consumerId;

    /**
     * @return the id of the consumer to be configured with basic auth
     * 
     */
    public Output<String> consumerId() {
        return this.consumerId;
    }

    /**
     * password to be used for basic auth
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return password to be used for basic auth
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    /**
     * A list of strings associated with the consumer basic auth for grouping and filtering
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<String>> tags;

    /**
     * @return A list of strings associated with the consumer basic auth for grouping and filtering
     * 
     */
    public Optional<Output<List<String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * username to be used for basic auth
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return username to be used for basic auth
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private ConsumerBasicAuthArgs() {}

    private ConsumerBasicAuthArgs(ConsumerBasicAuthArgs $) {
        this.consumerId = $.consumerId;
        this.password = $.password;
        this.tags = $.tags;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsumerBasicAuthArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsumerBasicAuthArgs $;

        public Builder() {
            $ = new ConsumerBasicAuthArgs();
        }

        public Builder(ConsumerBasicAuthArgs defaults) {
            $ = new ConsumerBasicAuthArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param consumerId the id of the consumer to be configured with basic auth
         * 
         * @return builder
         * 
         */
        public Builder consumerId(Output<String> consumerId) {
            $.consumerId = consumerId;
            return this;
        }

        /**
         * @param consumerId the id of the consumer to be configured with basic auth
         * 
         * @return builder
         * 
         */
        public Builder consumerId(String consumerId) {
            return consumerId(Output.of(consumerId));
        }

        /**
         * @param password password to be used for basic auth
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password password to be used for basic auth
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param tags A list of strings associated with the consumer basic auth for grouping and filtering
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags A list of strings associated with the consumer basic auth for grouping and filtering
         * 
         * @return builder
         * 
         */
        public Builder tags(List<String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags A list of strings associated with the consumer basic auth for grouping and filtering
         * 
         * @return builder
         * 
         */
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }

        /**
         * @param username username to be used for basic auth
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username username to be used for basic auth
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public ConsumerBasicAuthArgs build() {
            $.consumerId = Objects.requireNonNull($.consumerId, "expected parameter 'consumerId' to be non-null");
            $.password = Objects.requireNonNull($.password, "expected parameter 'password' to be non-null");
            $.username = Objects.requireNonNull($.username, "expected parameter 'username' to be non-null");
            return $;
        }
    }

}
