// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.kong.ConsumerOauth2Args;
import com.pulumi.kong.Utilities;
import com.pulumi.kong.inputs.ConsumerOauth2State;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## # kong.ConsumerOauth2
 * 
 * Resource that allows you to configure the OAuth2 plugin credentials for a consumer.
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.kong.Consumer;
 * import com.pulumi.kong.ConsumerArgs;
 * import com.pulumi.kong.Plugin;
 * import com.pulumi.kong.PluginArgs;
 * import com.pulumi.kong.ConsumerOauth2;
 * import com.pulumi.kong.ConsumerOauth2Args;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var myConsumer = new Consumer(&#34;myConsumer&#34;, ConsumerArgs.builder()        
 *             .customId(&#34;123&#34;)
 *             .username(&#34;User1&#34;)
 *             .build());
 * 
 *         var oauth2Plugin = new Plugin(&#34;oauth2Plugin&#34;, PluginArgs.builder()        
 *             .configJson(&#34;&#34;&#34;
 * 	{
 * 		&#34;global_credentials&#34;: true,
 * 		&#34;enable_password_grant&#34;: true,
 * 		&#34;token_expiration&#34;: 180,
 * 		&#34;refresh_token_ttl&#34;: 180,
 * 		&#34;provision_key&#34;: &#34;testprovisionkey&#34;
 * 	}
 * 
 *             &#34;&#34;&#34;)
 *             .build());
 * 
 *         var consumerOauth2 = new ConsumerOauth2(&#34;consumerOauth2&#34;, ConsumerOauth2Args.builder()        
 *             .clientId(&#34;client_id&#34;)
 *             .clientSecret(&#34;client_secret&#34;)
 *             .consumerId(myConsumer.id())
 *             .redirectUris(            
 *                 &#34;https://asdf.com/callback&#34;,
 *                 &#34;https://test.cl/callback&#34;)
 *             .tags(&#34;myTag&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="kong:index/consumerOauth2:ConsumerOauth2")
public class ConsumerOauth2 extends com.pulumi.resources.CustomResource {
    /**
     * Unique oauth2 client id. If not set, the oauth2 plugin will generate one
     * 
     */
    @Export(name="clientId", type=String.class, parameters={})
    private Output</* @Nullable */ String> clientId;

    /**
     * @return Unique oauth2 client id. If not set, the oauth2 plugin will generate one
     * 
     */
    public Output<Optional<String>> clientId() {
        return Codegen.optional(this.clientId);
    }
    /**
     * Unique oauth2 client secret. If not set, the oauth2 plugin will generate one
     * 
     */
    @Export(name="clientSecret", type=String.class, parameters={})
    private Output</* @Nullable */ String> clientSecret;

    /**
     * @return Unique oauth2 client secret. If not set, the oauth2 plugin will generate one
     * 
     */
    public Output<Optional<String>> clientSecret() {
        return Codegen.optional(this.clientSecret);
    }
    /**
     * The id of the consumer to be configured with oauth2.
     * 
     */
    @Export(name="consumerId", type=String.class, parameters={})
    private Output<String> consumerId;

    /**
     * @return The id of the consumer to be configured with oauth2.
     * 
     */
    public Output<String> consumerId() {
        return this.consumerId;
    }
    /**
     * A boolean flag that indicates whether the client_secret field will be stored in hashed form. If enabled on existing plugin instances, client secrets are hashed on the fly upon first usage. Default: `false`.
     * 
     */
    @Export(name="hashSecret", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> hashSecret;

    /**
     * @return A boolean flag that indicates whether the client_secret field will be stored in hashed form. If enabled on existing plugin instances, client secrets are hashed on the fly upon first usage. Default: `false`.
     * 
     */
    public Output<Optional<Boolean>> hashSecret() {
        return Codegen.optional(this.hashSecret);
    }
    /**
     * The name associated with the credential.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The name associated with the credential.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * An array with one or more URLs in your app where users will be sent after authorization ([RFC 6742 Section 3.1.2](https://tools.ietf.org/html/rfc6749#section-3.1.2)).
     * 
     */
    @Export(name="redirectUris", type=List.class, parameters={String.class})
    private Output<List<String>> redirectUris;

    /**
     * @return An array with one or more URLs in your app where users will be sent after authorization ([RFC 6742 Section 3.1.2](https://tools.ietf.org/html/rfc6749#section-3.1.2)).
     * 
     */
    public Output<List<String>> redirectUris() {
        return this.redirectUris;
    }
    /**
     * A list of strings associated with the consumer for grouping and filtering.
     * 
     */
    @Export(name="tags", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return A list of strings associated with the consumer for grouping and filtering.
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ConsumerOauth2(String name) {
        this(name, ConsumerOauth2Args.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ConsumerOauth2(String name, ConsumerOauth2Args args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ConsumerOauth2(String name, ConsumerOauth2Args args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("kong:index/consumerOauth2:ConsumerOauth2", name, args == null ? ConsumerOauth2Args.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ConsumerOauth2(String name, Output<String> id, @Nullable ConsumerOauth2State state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("kong:index/consumerOauth2:ConsumerOauth2", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ConsumerOauth2 get(String name, Output<String> id, @Nullable ConsumerOauth2State state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ConsumerOauth2(name, id, state, options);
    }
}
