// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.kong.ConsumerBasicAuthArgs;
import com.pulumi.kong.Utilities;
import com.pulumi.kong.inputs.ConsumerBasicAuthState;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## # kong.ConsumerBasicAuth
 * 
 * Consumer basic auth is a resource that allows you to configure the basic auth plugin for a consumer.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.kong.Consumer;
 * import com.pulumi.kong.ConsumerArgs;
 * import com.pulumi.kong.Plugin;
 * import com.pulumi.kong.PluginArgs;
 * import com.pulumi.kong.ConsumerBasicAuth;
 * import com.pulumi.kong.ConsumerBasicAuthArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var myConsumer = new Consumer("myConsumer", ConsumerArgs.builder()        
 *             .username("User1")
 *             .customId("123")
 *             .build());
 * 
 *         var basicAuthPlugin = new Plugin("basicAuthPlugin", PluginArgs.builder()        
 *             .name("basic-auth")
 *             .build());
 * 
 *         var consumerBasicAuth = new ConsumerBasicAuth("consumerBasicAuth", ConsumerBasicAuthArgs.builder()        
 *             .consumerId(myConsumer.id())
 *             .username("foo_updated")
 *             .password("bar_updated")
 *             .tags(            
 *                 "myTag",
 *                 "anotherTag")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="kong:index/consumerBasicAuth:ConsumerBasicAuth")
public class ConsumerBasicAuth extends com.pulumi.resources.CustomResource {
    /**
     * the id of the consumer to be configured with basic auth
     * 
     */
    @Export(name="consumerId", refs={String.class}, tree="[0]")
    private Output<String> consumerId;

    /**
     * @return the id of the consumer to be configured with basic auth
     * 
     */
    public Output<String> consumerId() {
        return this.consumerId;
    }
    /**
     * password to be used for basic auth
     * 
     */
    @Export(name="password", refs={String.class}, tree="[0]")
    private Output<String> password;

    /**
     * @return password to be used for basic auth
     * 
     */
    public Output<String> password() {
        return this.password;
    }
    /**
     * A list of strings associated with the consumer basic auth for grouping and filtering
     * 
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return A list of strings associated with the consumer basic auth for grouping and filtering
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * username to be used for basic auth
     * 
     */
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output<String> username;

    /**
     * @return username to be used for basic auth
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ConsumerBasicAuth(String name) {
        this(name, ConsumerBasicAuthArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ConsumerBasicAuth(String name, ConsumerBasicAuthArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ConsumerBasicAuth(String name, ConsumerBasicAuthArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("kong:index/consumerBasicAuth:ConsumerBasicAuth", name, args == null ? ConsumerBasicAuthArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ConsumerBasicAuth(String name, Output<String> id, @Nullable ConsumerBasicAuthState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("kong:index/consumerBasicAuth:ConsumerBasicAuth", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ConsumerBasicAuth get(String name, Output<String> id, @Nullable ConsumerBasicAuthState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ConsumerBasicAuth(name, id, state, options);
    }
}
