// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.kong.PluginArgs;
import com.pulumi.kong.Utilities;
import com.pulumi.kong.inputs.PluginState;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## # kong.Plugin
 * 
 * The plugin resource maps directly onto the json for the API endpoint in Kong.  For more information on the parameters [see the Kong Api create documentation](https://docs.konghq.com/gateway-oss/2.5.x/admin-api/#plugin-object).
 * The `config_json` is passed through to the plugin to configure it as is.
 * 
 * ## Example Usage
 * 
 * ## Import
 * 
 * To import a plugin
 * 
 * ```sh
 *  $ pulumi import kong:index/plugin:Plugin &lt;plugin_identifier&gt; &lt;plugin_id&gt;
 * ```
 * 
 */
@ResourceType(type="kong:index/plugin:Plugin")
public class Plugin extends com.pulumi.resources.CustomResource {
    @Export(name="computedConfig", type=String.class, parameters={})
    private Output<String> computedConfig;

    public Output<String> computedConfig() {
        return this.computedConfig;
    }
    /**
     * this is the configuration json for how you want to configure the plugin.  The json is passed straight through to kong as is.  You can get the json config from the Kong documentation
     * page of the plugin you are configuring
     * 
     */
    @Export(name="configJson", type=String.class, parameters={})
    private Output</* @Nullable */ String> configJson;

    /**
     * @return this is the configuration json for how you want to configure the plugin.  The json is passed straight through to kong as is.  You can get the json config from the Kong documentation
     * page of the plugin you are configuring
     * 
     */
    public Output<Optional<String>> configJson() {
        return Codegen.optional(this.configJson);
    }
    /**
     * the consumer id you want to configure the plugin for
     * 
     */
    @Export(name="consumerId", type=String.class, parameters={})
    private Output</* @Nullable */ String> consumerId;

    /**
     * @return the consumer id you want to configure the plugin for
     * 
     */
    public Output<Optional<String>> consumerId() {
        return Codegen.optional(this.consumerId);
    }
    /**
     * whether the plugin is enabled or not, use if you want to keep the plugin installed but disable it
     * 
     */
    @Export(name="enabled", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> enabled;

    /**
     * @return whether the plugin is enabled or not, use if you want to keep the plugin installed but disable it
     * 
     */
    public Output<Optional<Boolean>> enabled() {
        return Codegen.optional(this.enabled);
    }
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    /**
     * the route id that you want to configure the plugin for
     * 
     */
    @Export(name="routeId", type=String.class, parameters={})
    private Output</* @Nullable */ String> routeId;

    /**
     * @return the route id that you want to configure the plugin for
     * 
     */
    public Output<Optional<String>> routeId() {
        return Codegen.optional(this.routeId);
    }
    /**
     * the service id that you want to configure the plugin for
     * 
     */
    @Export(name="serviceId", type=String.class, parameters={})
    private Output</* @Nullable */ String> serviceId;

    /**
     * @return the service id that you want to configure the plugin for
     * 
     */
    public Output<Optional<String>> serviceId() {
        return Codegen.optional(this.serviceId);
    }
    @Export(name="strictMatch", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> strictMatch;

    public Output<Optional<Boolean>> strictMatch() {
        return Codegen.optional(this.strictMatch);
    }
    /**
     * A list of strings associated with the Plugin for grouping and filtering
     * 
     */
    @Export(name="tags", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return A list of strings associated with the Plugin for grouping and filtering
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Plugin(String name) {
        this(name, PluginArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Plugin(String name, @Nullable PluginArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Plugin(String name, @Nullable PluginArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("kong:index/plugin:Plugin", name, args == null ? PluginArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Plugin(String name, Output<String> id, @Nullable PluginState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("kong:index/plugin:Plugin", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Plugin get(String name, Output<String> id, @Nullable PluginState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Plugin(name, id, state, options);
    }
}
