// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kong

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-kong/sdk/v4/go/kong/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Consumer
//
// The consumer resource maps directly onto the json for creating a Consumer in Kong.  For more information on the parameters [see the Kong Consumer create documentation](https://docs.konghq.com/gateway-oss/2.5.x/admin-api/#consumer-object).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-kong/sdk/v4/go/kong"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := kong.NewConsumer(ctx, "consumer", &kong.ConsumerArgs{
//				Username: pulumi.String("User1"),
//				CustomId: pulumi.String("123"),
//				Tags: pulumi.StringArray{
//					pulumi.String("mySuperTag"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// To import a consumer:
//
// ```sh
// $ pulumi import kong:index/consumer:Consumer <consumer_identifier> <consumer_id>
// ```
type Consumer struct {
	pulumi.CustomResourceState

	// A custom id for the consumer, you must set either the username or custom_id
	CustomId pulumi.StringPtrOutput `pulumi:"customId"`
	// A list of strings associated with the Consumer for grouping and filtering
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// The username to use, you must set either the username or custom_id
	Username pulumi.StringPtrOutput `pulumi:"username"`
}

// NewConsumer registers a new resource with the given unique name, arguments, and options.
func NewConsumer(ctx *pulumi.Context,
	name string, args *ConsumerArgs, opts ...pulumi.ResourceOption) (*Consumer, error) {
	if args == nil {
		args = &ConsumerArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Consumer
	err := ctx.RegisterResource("kong:index/consumer:Consumer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConsumer gets an existing Consumer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConsumer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConsumerState, opts ...pulumi.ResourceOption) (*Consumer, error) {
	var resource Consumer
	err := ctx.ReadResource("kong:index/consumer:Consumer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Consumer resources.
type consumerState struct {
	// A custom id for the consumer, you must set either the username or custom_id
	CustomId *string `pulumi:"customId"`
	// A list of strings associated with the Consumer for grouping and filtering
	Tags []string `pulumi:"tags"`
	// The username to use, you must set either the username or custom_id
	Username *string `pulumi:"username"`
}

type ConsumerState struct {
	// A custom id for the consumer, you must set either the username or custom_id
	CustomId pulumi.StringPtrInput
	// A list of strings associated with the Consumer for grouping and filtering
	Tags pulumi.StringArrayInput
	// The username to use, you must set either the username or custom_id
	Username pulumi.StringPtrInput
}

func (ConsumerState) ElementType() reflect.Type {
	return reflect.TypeOf((*consumerState)(nil)).Elem()
}

type consumerArgs struct {
	// A custom id for the consumer, you must set either the username or custom_id
	CustomId *string `pulumi:"customId"`
	// A list of strings associated with the Consumer for grouping and filtering
	Tags []string `pulumi:"tags"`
	// The username to use, you must set either the username or custom_id
	Username *string `pulumi:"username"`
}

// The set of arguments for constructing a Consumer resource.
type ConsumerArgs struct {
	// A custom id for the consumer, you must set either the username or custom_id
	CustomId pulumi.StringPtrInput
	// A list of strings associated with the Consumer for grouping and filtering
	Tags pulumi.StringArrayInput
	// The username to use, you must set either the username or custom_id
	Username pulumi.StringPtrInput
}

func (ConsumerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*consumerArgs)(nil)).Elem()
}

type ConsumerInput interface {
	pulumi.Input

	ToConsumerOutput() ConsumerOutput
	ToConsumerOutputWithContext(ctx context.Context) ConsumerOutput
}

func (*Consumer) ElementType() reflect.Type {
	return reflect.TypeOf((**Consumer)(nil)).Elem()
}

func (i *Consumer) ToConsumerOutput() ConsumerOutput {
	return i.ToConsumerOutputWithContext(context.Background())
}

func (i *Consumer) ToConsumerOutputWithContext(ctx context.Context) ConsumerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerOutput)
}

// ConsumerArrayInput is an input type that accepts ConsumerArray and ConsumerArrayOutput values.
// You can construct a concrete instance of `ConsumerArrayInput` via:
//
//	ConsumerArray{ ConsumerArgs{...} }
type ConsumerArrayInput interface {
	pulumi.Input

	ToConsumerArrayOutput() ConsumerArrayOutput
	ToConsumerArrayOutputWithContext(context.Context) ConsumerArrayOutput
}

type ConsumerArray []ConsumerInput

func (ConsumerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Consumer)(nil)).Elem()
}

func (i ConsumerArray) ToConsumerArrayOutput() ConsumerArrayOutput {
	return i.ToConsumerArrayOutputWithContext(context.Background())
}

func (i ConsumerArray) ToConsumerArrayOutputWithContext(ctx context.Context) ConsumerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerArrayOutput)
}

// ConsumerMapInput is an input type that accepts ConsumerMap and ConsumerMapOutput values.
// You can construct a concrete instance of `ConsumerMapInput` via:
//
//	ConsumerMap{ "key": ConsumerArgs{...} }
type ConsumerMapInput interface {
	pulumi.Input

	ToConsumerMapOutput() ConsumerMapOutput
	ToConsumerMapOutputWithContext(context.Context) ConsumerMapOutput
}

type ConsumerMap map[string]ConsumerInput

func (ConsumerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Consumer)(nil)).Elem()
}

func (i ConsumerMap) ToConsumerMapOutput() ConsumerMapOutput {
	return i.ToConsumerMapOutputWithContext(context.Background())
}

func (i ConsumerMap) ToConsumerMapOutputWithContext(ctx context.Context) ConsumerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerMapOutput)
}

type ConsumerOutput struct{ *pulumi.OutputState }

func (ConsumerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Consumer)(nil)).Elem()
}

func (o ConsumerOutput) ToConsumerOutput() ConsumerOutput {
	return o
}

func (o ConsumerOutput) ToConsumerOutputWithContext(ctx context.Context) ConsumerOutput {
	return o
}

// A custom id for the consumer, you must set either the username or custom_id
func (o ConsumerOutput) CustomId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Consumer) pulumi.StringPtrOutput { return v.CustomId }).(pulumi.StringPtrOutput)
}

// A list of strings associated with the Consumer for grouping and filtering
func (o ConsumerOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Consumer) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// The username to use, you must set either the username or custom_id
func (o ConsumerOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Consumer) pulumi.StringPtrOutput { return v.Username }).(pulumi.StringPtrOutput)
}

type ConsumerArrayOutput struct{ *pulumi.OutputState }

func (ConsumerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Consumer)(nil)).Elem()
}

func (o ConsumerArrayOutput) ToConsumerArrayOutput() ConsumerArrayOutput {
	return o
}

func (o ConsumerArrayOutput) ToConsumerArrayOutputWithContext(ctx context.Context) ConsumerArrayOutput {
	return o
}

func (o ConsumerArrayOutput) Index(i pulumi.IntInput) ConsumerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Consumer {
		return vs[0].([]*Consumer)[vs[1].(int)]
	}).(ConsumerOutput)
}

type ConsumerMapOutput struct{ *pulumi.OutputState }

func (ConsumerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Consumer)(nil)).Elem()
}

func (o ConsumerMapOutput) ToConsumerMapOutput() ConsumerMapOutput {
	return o
}

func (o ConsumerMapOutput) ToConsumerMapOutputWithContext(ctx context.Context) ConsumerMapOutput {
	return o
}

func (o ConsumerMapOutput) MapIndex(k pulumi.StringInput) ConsumerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Consumer {
		return vs[0].(map[string]*Consumer)[vs[1].(string)]
	}).(ConsumerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConsumerInput)(nil)).Elem(), &Consumer{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConsumerArrayInput)(nil)).Elem(), ConsumerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConsumerMapInput)(nil)).Elem(), ConsumerMap{})
	pulumi.RegisterOutputType(ConsumerOutput{})
	pulumi.RegisterOutputType(ConsumerArrayOutput{})
	pulumi.RegisterOutputType(ConsumerMapOutput{})
}
