// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package kong

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ConsumerBasicAuth struct {
	pulumi.CustomResourceState

	ConsumerId pulumi.StringOutput      `pulumi:"consumerId"`
	Password   pulumi.StringOutput      `pulumi:"password"`
	Tags       pulumi.StringArrayOutput `pulumi:"tags"`
	Username   pulumi.StringOutput      `pulumi:"username"`
}

// NewConsumerBasicAuth registers a new resource with the given unique name, arguments, and options.
func NewConsumerBasicAuth(ctx *pulumi.Context,
	name string, args *ConsumerBasicAuthArgs, opts ...pulumi.ResourceOption) (*ConsumerBasicAuth, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConsumerId == nil {
		return nil, errors.New("invalid value for required argument 'ConsumerId'")
	}
	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	var resource ConsumerBasicAuth
	err := ctx.RegisterResource("kong:index/consumerBasicAuth:ConsumerBasicAuth", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConsumerBasicAuth gets an existing ConsumerBasicAuth resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConsumerBasicAuth(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConsumerBasicAuthState, opts ...pulumi.ResourceOption) (*ConsumerBasicAuth, error) {
	var resource ConsumerBasicAuth
	err := ctx.ReadResource("kong:index/consumerBasicAuth:ConsumerBasicAuth", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ConsumerBasicAuth resources.
type consumerBasicAuthState struct {
	ConsumerId *string  `pulumi:"consumerId"`
	Password   *string  `pulumi:"password"`
	Tags       []string `pulumi:"tags"`
	Username   *string  `pulumi:"username"`
}

type ConsumerBasicAuthState struct {
	ConsumerId pulumi.StringPtrInput
	Password   pulumi.StringPtrInput
	Tags       pulumi.StringArrayInput
	Username   pulumi.StringPtrInput
}

func (ConsumerBasicAuthState) ElementType() reflect.Type {
	return reflect.TypeOf((*consumerBasicAuthState)(nil)).Elem()
}

type consumerBasicAuthArgs struct {
	ConsumerId string   `pulumi:"consumerId"`
	Password   string   `pulumi:"password"`
	Tags       []string `pulumi:"tags"`
	Username   string   `pulumi:"username"`
}

// The set of arguments for constructing a ConsumerBasicAuth resource.
type ConsumerBasicAuthArgs struct {
	ConsumerId pulumi.StringInput
	Password   pulumi.StringInput
	Tags       pulumi.StringArrayInput
	Username   pulumi.StringInput
}

func (ConsumerBasicAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*consumerBasicAuthArgs)(nil)).Elem()
}

type ConsumerBasicAuthInput interface {
	pulumi.Input

	ToConsumerBasicAuthOutput() ConsumerBasicAuthOutput
	ToConsumerBasicAuthOutputWithContext(ctx context.Context) ConsumerBasicAuthOutput
}

func (*ConsumerBasicAuth) ElementType() reflect.Type {
	return reflect.TypeOf((*ConsumerBasicAuth)(nil))
}

func (i *ConsumerBasicAuth) ToConsumerBasicAuthOutput() ConsumerBasicAuthOutput {
	return i.ToConsumerBasicAuthOutputWithContext(context.Background())
}

func (i *ConsumerBasicAuth) ToConsumerBasicAuthOutputWithContext(ctx context.Context) ConsumerBasicAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerBasicAuthOutput)
}

func (i *ConsumerBasicAuth) ToConsumerBasicAuthPtrOutput() ConsumerBasicAuthPtrOutput {
	return i.ToConsumerBasicAuthPtrOutputWithContext(context.Background())
}

func (i *ConsumerBasicAuth) ToConsumerBasicAuthPtrOutputWithContext(ctx context.Context) ConsumerBasicAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerBasicAuthPtrOutput)
}

type ConsumerBasicAuthPtrInput interface {
	pulumi.Input

	ToConsumerBasicAuthPtrOutput() ConsumerBasicAuthPtrOutput
	ToConsumerBasicAuthPtrOutputWithContext(ctx context.Context) ConsumerBasicAuthPtrOutput
}

type consumerBasicAuthPtrType ConsumerBasicAuthArgs

func (*consumerBasicAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ConsumerBasicAuth)(nil))
}

func (i *consumerBasicAuthPtrType) ToConsumerBasicAuthPtrOutput() ConsumerBasicAuthPtrOutput {
	return i.ToConsumerBasicAuthPtrOutputWithContext(context.Background())
}

func (i *consumerBasicAuthPtrType) ToConsumerBasicAuthPtrOutputWithContext(ctx context.Context) ConsumerBasicAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerBasicAuthPtrOutput)
}

// ConsumerBasicAuthArrayInput is an input type that accepts ConsumerBasicAuthArray and ConsumerBasicAuthArrayOutput values.
// You can construct a concrete instance of `ConsumerBasicAuthArrayInput` via:
//
//          ConsumerBasicAuthArray{ ConsumerBasicAuthArgs{...} }
type ConsumerBasicAuthArrayInput interface {
	pulumi.Input

	ToConsumerBasicAuthArrayOutput() ConsumerBasicAuthArrayOutput
	ToConsumerBasicAuthArrayOutputWithContext(context.Context) ConsumerBasicAuthArrayOutput
}

type ConsumerBasicAuthArray []ConsumerBasicAuthInput

func (ConsumerBasicAuthArray) ElementType() reflect.Type {
	return reflect.TypeOf(([]*ConsumerBasicAuth)(nil))
}

func (i ConsumerBasicAuthArray) ToConsumerBasicAuthArrayOutput() ConsumerBasicAuthArrayOutput {
	return i.ToConsumerBasicAuthArrayOutputWithContext(context.Background())
}

func (i ConsumerBasicAuthArray) ToConsumerBasicAuthArrayOutputWithContext(ctx context.Context) ConsumerBasicAuthArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerBasicAuthArrayOutput)
}

// ConsumerBasicAuthMapInput is an input type that accepts ConsumerBasicAuthMap and ConsumerBasicAuthMapOutput values.
// You can construct a concrete instance of `ConsumerBasicAuthMapInput` via:
//
//          ConsumerBasicAuthMap{ "key": ConsumerBasicAuthArgs{...} }
type ConsumerBasicAuthMapInput interface {
	pulumi.Input

	ToConsumerBasicAuthMapOutput() ConsumerBasicAuthMapOutput
	ToConsumerBasicAuthMapOutputWithContext(context.Context) ConsumerBasicAuthMapOutput
}

type ConsumerBasicAuthMap map[string]ConsumerBasicAuthInput

func (ConsumerBasicAuthMap) ElementType() reflect.Type {
	return reflect.TypeOf((map[string]*ConsumerBasicAuth)(nil))
}

func (i ConsumerBasicAuthMap) ToConsumerBasicAuthMapOutput() ConsumerBasicAuthMapOutput {
	return i.ToConsumerBasicAuthMapOutputWithContext(context.Background())
}

func (i ConsumerBasicAuthMap) ToConsumerBasicAuthMapOutputWithContext(ctx context.Context) ConsumerBasicAuthMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsumerBasicAuthMapOutput)
}

type ConsumerBasicAuthOutput struct {
	*pulumi.OutputState
}

func (ConsumerBasicAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ConsumerBasicAuth)(nil))
}

func (o ConsumerBasicAuthOutput) ToConsumerBasicAuthOutput() ConsumerBasicAuthOutput {
	return o
}

func (o ConsumerBasicAuthOutput) ToConsumerBasicAuthOutputWithContext(ctx context.Context) ConsumerBasicAuthOutput {
	return o
}

func (o ConsumerBasicAuthOutput) ToConsumerBasicAuthPtrOutput() ConsumerBasicAuthPtrOutput {
	return o.ToConsumerBasicAuthPtrOutputWithContext(context.Background())
}

func (o ConsumerBasicAuthOutput) ToConsumerBasicAuthPtrOutputWithContext(ctx context.Context) ConsumerBasicAuthPtrOutput {
	return o.ApplyT(func(v ConsumerBasicAuth) *ConsumerBasicAuth {
		return &v
	}).(ConsumerBasicAuthPtrOutput)
}

type ConsumerBasicAuthPtrOutput struct {
	*pulumi.OutputState
}

func (ConsumerBasicAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ConsumerBasicAuth)(nil))
}

func (o ConsumerBasicAuthPtrOutput) ToConsumerBasicAuthPtrOutput() ConsumerBasicAuthPtrOutput {
	return o
}

func (o ConsumerBasicAuthPtrOutput) ToConsumerBasicAuthPtrOutputWithContext(ctx context.Context) ConsumerBasicAuthPtrOutput {
	return o
}

type ConsumerBasicAuthArrayOutput struct{ *pulumi.OutputState }

func (ConsumerBasicAuthArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ConsumerBasicAuth)(nil))
}

func (o ConsumerBasicAuthArrayOutput) ToConsumerBasicAuthArrayOutput() ConsumerBasicAuthArrayOutput {
	return o
}

func (o ConsumerBasicAuthArrayOutput) ToConsumerBasicAuthArrayOutputWithContext(ctx context.Context) ConsumerBasicAuthArrayOutput {
	return o
}

func (o ConsumerBasicAuthArrayOutput) Index(i pulumi.IntInput) ConsumerBasicAuthOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ConsumerBasicAuth {
		return vs[0].([]ConsumerBasicAuth)[vs[1].(int)]
	}).(ConsumerBasicAuthOutput)
}

type ConsumerBasicAuthMapOutput struct{ *pulumi.OutputState }

func (ConsumerBasicAuthMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ConsumerBasicAuth)(nil))
}

func (o ConsumerBasicAuthMapOutput) ToConsumerBasicAuthMapOutput() ConsumerBasicAuthMapOutput {
	return o
}

func (o ConsumerBasicAuthMapOutput) ToConsumerBasicAuthMapOutputWithContext(ctx context.Context) ConsumerBasicAuthMapOutput {
	return o
}

func (o ConsumerBasicAuthMapOutput) MapIndex(k pulumi.StringInput) ConsumerBasicAuthOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ConsumerBasicAuth {
		return vs[0].(map[string]ConsumerBasicAuth)[vs[1].(string)]
	}).(ConsumerBasicAuthOutput)
}

func init() {
	pulumi.RegisterOutputType(ConsumerBasicAuthOutput{})
	pulumi.RegisterOutputType(ConsumerBasicAuthPtrOutput{})
	pulumi.RegisterOutputType(ConsumerBasicAuthArrayOutput{})
	pulumi.RegisterOutputType(ConsumerBasicAuthMapOutput{})
}
