provider: kong
major-version: 4
docker: true
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
plugins:
    - name: terraform
      version: "1.0.16"
      kind: converter
esc:
    enabled: true
