// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RouteDestinationArgs extends com.pulumi.resources.ResourceArgs {

    public static final RouteDestinationArgs Empty = new RouteDestinationArgs();

    @Import(name="ip")
    private @Nullable Output<String> ip;

    public Optional<Output<String>> ip() {
        return Optional.ofNullable(this.ip);
    }

    @Import(name="port")
    private @Nullable Output<Integer> port;

    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    private RouteDestinationArgs() {}

    private RouteDestinationArgs(RouteDestinationArgs $) {
        this.ip = $.ip;
        this.port = $.port;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RouteDestinationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RouteDestinationArgs $;

        public Builder() {
            $ = new RouteDestinationArgs();
        }

        public Builder(RouteDestinationArgs defaults) {
            $ = new RouteDestinationArgs(Objects.requireNonNull(defaults));
        }

        public Builder ip(@Nullable Output<String> ip) {
            $.ip = ip;
            return this;
        }

        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        public RouteDestinationArgs build() {
            return $;
        }
    }

}
