// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UpstreamHealthchecksActiveHealthyArgs extends com.pulumi.resources.ResourceArgs {

    public static final UpstreamHealthchecksActiveHealthyArgs Empty = new UpstreamHealthchecksActiveHealthyArgs();

    @Import(name="httpStatuses")
    private @Nullable Output<List<Integer>> httpStatuses;

    public Optional<Output<List<Integer>>> httpStatuses() {
        return Optional.ofNullable(this.httpStatuses);
    }

    @Import(name="interval")
    private @Nullable Output<Integer> interval;

    public Optional<Output<Integer>> interval() {
        return Optional.ofNullable(this.interval);
    }

    @Import(name="successes")
    private @Nullable Output<Integer> successes;

    public Optional<Output<Integer>> successes() {
        return Optional.ofNullable(this.successes);
    }

    private UpstreamHealthchecksActiveHealthyArgs() {}

    private UpstreamHealthchecksActiveHealthyArgs(UpstreamHealthchecksActiveHealthyArgs $) {
        this.httpStatuses = $.httpStatuses;
        this.interval = $.interval;
        this.successes = $.successes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UpstreamHealthchecksActiveHealthyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UpstreamHealthchecksActiveHealthyArgs $;

        public Builder() {
            $ = new UpstreamHealthchecksActiveHealthyArgs();
        }

        public Builder(UpstreamHealthchecksActiveHealthyArgs defaults) {
            $ = new UpstreamHealthchecksActiveHealthyArgs(Objects.requireNonNull(defaults));
        }

        public Builder httpStatuses(@Nullable Output<List<Integer>> httpStatuses) {
            $.httpStatuses = httpStatuses;
            return this;
        }

        public Builder httpStatuses(List<Integer> httpStatuses) {
            return httpStatuses(Output.of(httpStatuses));
        }

        public Builder httpStatuses(Integer... httpStatuses) {
            return httpStatuses(List.of(httpStatuses));
        }

        public Builder interval(@Nullable Output<Integer> interval) {
            $.interval = interval;
            return this;
        }

        public Builder interval(Integer interval) {
            return interval(Output.of(interval));
        }

        public Builder successes(@Nullable Output<Integer> successes) {
            $.successes = successes;
            return this;
        }

        public Builder successes(Integer successes) {
            return successes(Output.of(successes));
        }

        public UpstreamHealthchecksActiveHealthyArgs build() {
            return $;
        }
    }

}
