// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kong.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UpstreamHealthchecksActiveUnhealthyArgs extends com.pulumi.resources.ResourceArgs {

    public static final UpstreamHealthchecksActiveUnhealthyArgs Empty = new UpstreamHealthchecksActiveUnhealthyArgs();

    @Import(name="httpFailures")
    private @Nullable Output<Integer> httpFailures;

    public Optional<Output<Integer>> httpFailures() {
        return Optional.ofNullable(this.httpFailures);
    }

    @Import(name="httpStatuses")
    private @Nullable Output<List<Integer>> httpStatuses;

    public Optional<Output<List<Integer>>> httpStatuses() {
        return Optional.ofNullable(this.httpStatuses);
    }

    @Import(name="interval")
    private @Nullable Output<Integer> interval;

    public Optional<Output<Integer>> interval() {
        return Optional.ofNullable(this.interval);
    }

    @Import(name="tcpFailures")
    private @Nullable Output<Integer> tcpFailures;

    public Optional<Output<Integer>> tcpFailures() {
        return Optional.ofNullable(this.tcpFailures);
    }

    @Import(name="timeouts")
    private @Nullable Output<Integer> timeouts;

    public Optional<Output<Integer>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    private UpstreamHealthchecksActiveUnhealthyArgs() {}

    private UpstreamHealthchecksActiveUnhealthyArgs(UpstreamHealthchecksActiveUnhealthyArgs $) {
        this.httpFailures = $.httpFailures;
        this.httpStatuses = $.httpStatuses;
        this.interval = $.interval;
        this.tcpFailures = $.tcpFailures;
        this.timeouts = $.timeouts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UpstreamHealthchecksActiveUnhealthyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UpstreamHealthchecksActiveUnhealthyArgs $;

        public Builder() {
            $ = new UpstreamHealthchecksActiveUnhealthyArgs();
        }

        public Builder(UpstreamHealthchecksActiveUnhealthyArgs defaults) {
            $ = new UpstreamHealthchecksActiveUnhealthyArgs(Objects.requireNonNull(defaults));
        }

        public Builder httpFailures(@Nullable Output<Integer> httpFailures) {
            $.httpFailures = httpFailures;
            return this;
        }

        public Builder httpFailures(Integer httpFailures) {
            return httpFailures(Output.of(httpFailures));
        }

        public Builder httpStatuses(@Nullable Output<List<Integer>> httpStatuses) {
            $.httpStatuses = httpStatuses;
            return this;
        }

        public Builder httpStatuses(List<Integer> httpStatuses) {
            return httpStatuses(Output.of(httpStatuses));
        }

        public Builder httpStatuses(Integer... httpStatuses) {
            return httpStatuses(List.of(httpStatuses));
        }

        public Builder interval(@Nullable Output<Integer> interval) {
            $.interval = interval;
            return this;
        }

        public Builder interval(Integer interval) {
            return interval(Output.of(interval));
        }

        public Builder tcpFailures(@Nullable Output<Integer> tcpFailures) {
            $.tcpFailures = tcpFailures;
            return this;
        }

        public Builder tcpFailures(Integer tcpFailures) {
            return tcpFailures(Output.of(tcpFailures));
        }

        public Builder timeouts(@Nullable Output<Integer> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(Integer timeouts) {
            return timeouts(Output.of(timeouts));
        }

        public UpstreamHealthchecksActiveUnhealthyArgs build() {
            return $;
        }
    }

}
