// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kong.Outputs
{

    [OutputType]
    public sealed class UpstreamHealthchecksActiveHealthy
    {
        public readonly ImmutableArray<int> HttpStatuses;
        public readonly int? Interval;
        public readonly int? Successes;

        [OutputConstructor]
        private UpstreamHealthchecksActiveHealthy(
            ImmutableArray<int> httpStatuses,

            int? interval,

            int? successes)
        {
            HttpStatuses = httpStatuses;
            Interval = interval;
            Successes = successes;
        }
    }
}
