// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kong.Outputs
{

    [OutputType]
    public sealed class UpstreamHealthchecksPassiveUnhealthy
    {
        public readonly int? HttpFailures;
        public readonly ImmutableArray<int> HttpStatuses;
        public readonly int? TcpFailures;
        public readonly int? Timeouts;

        [OutputConstructor]
        private UpstreamHealthchecksPassiveUnhealthy(
            int? httpFailures,

            ImmutableArray<int> httpStatuses,

            int? tcpFailures,

            int? timeouts)
        {
            HttpFailures = httpFailures;
            HttpStatuses = httpStatuses;
            TcpFailures = tcpFailures;
            Timeouts = timeouts;
        }
    }
}
