// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kong.Outputs
{

    [OutputType]
    public sealed class UpstreamHealthchecks
    {
        public readonly Outputs.UpstreamHealthchecksActive? Active;
        public readonly Outputs.UpstreamHealthchecksPassive? Passive;

        [OutputConstructor]
        private UpstreamHealthchecks(
            Outputs.UpstreamHealthchecksActive? active,

            Outputs.UpstreamHealthchecksPassive? passive)
        {
            Active = active;
            Passive = passive;
        }
    }
}
