// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface RouteDestination {
    ip?: pulumi.Input<string | undefined>;
    port?: pulumi.Input<number | undefined>;
}

export interface RouteHeader {
    /**
     * The name of the route
     */
    name: pulumi.Input<string>;
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface RouteSource {
    ip?: pulumi.Input<string | undefined>;
    port?: pulumi.Input<number | undefined>;
}

export interface UpstreamHealthchecks {
    active?: pulumi.Input<inputs.UpstreamHealthchecksActive | undefined>;
    passive?: pulumi.Input<inputs.UpstreamHealthchecksPassive | undefined>;
}

export interface UpstreamHealthchecksActive {
    concurrency?: pulumi.Input<number | undefined>;
    healthy?: pulumi.Input<inputs.UpstreamHealthchecksActiveHealthy | undefined>;
    httpPath?: pulumi.Input<string | undefined>;
    httpsSni?: pulumi.Input<string | undefined>;
    httpsVerifyCertificate?: pulumi.Input<boolean | undefined>;
    timeout?: pulumi.Input<number | undefined>;
    type?: pulumi.Input<string | undefined>;
    unhealthy?: pulumi.Input<inputs.UpstreamHealthchecksActiveUnhealthy | undefined>;
}

export interface UpstreamHealthchecksActiveHealthy {
    httpStatuses?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    interval?: pulumi.Input<number | undefined>;
    successes?: pulumi.Input<number | undefined>;
}

export interface UpstreamHealthchecksActiveUnhealthy {
    httpFailures?: pulumi.Input<number | undefined>;
    httpStatuses?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    interval?: pulumi.Input<number | undefined>;
    tcpFailures?: pulumi.Input<number | undefined>;
    timeouts?: pulumi.Input<number | undefined>;
}

export interface UpstreamHealthchecksPassive {
    healthy?: pulumi.Input<inputs.UpstreamHealthchecksPassiveHealthy | undefined>;
    type?: pulumi.Input<string | undefined>;
    unhealthy?: pulumi.Input<inputs.UpstreamHealthchecksPassiveUnhealthy | undefined>;
}

export interface UpstreamHealthchecksPassiveHealthy {
    httpStatuses?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    successes?: pulumi.Input<number | undefined>;
}

export interface UpstreamHealthchecksPassiveUnhealthy {
    httpFailures?: pulumi.Input<number | undefined>;
    httpStatuses?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    tcpFailures?: pulumi.Input<number | undefined>;
    timeouts?: pulumi.Input<number | undefined>;
}
