// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kong.Inputs
{

    public sealed class UpstreamHealthchecksPassiveGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("healthy")]
        public Input<Inputs.UpstreamHealthchecksPassiveHealthyGetArgs>? Healthy { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("unhealthy")]
        public Input<Inputs.UpstreamHealthchecksPassiveUnhealthyGetArgs>? Unhealthy { get; set; }

        public UpstreamHealthchecksPassiveGetArgs()
        {
        }
        public static new UpstreamHealthchecksPassiveGetArgs Empty => new UpstreamHealthchecksPassiveGetArgs();
    }
}
