// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kong.Inputs
{

    public sealed class UpstreamHealthchecksArgs : Pulumi.ResourceArgs
    {
        [Input("active")]
        public Input<Inputs.UpstreamHealthchecksActiveArgs>? Active { get; set; }

        [Input("passive")]
        public Input<Inputs.UpstreamHealthchecksPassiveArgs>? Passive { get; set; }

        public UpstreamHealthchecksArgs()
        {
        }
    }
}
